### ISSUE TITLE
Feature: Add a jump animation

### ISSUE THREAD

**Issue by becckitt** [becckitt/blood-game#9]
Just for the hell of it.

There is an existing jump animation set for Peter, and this commented line at the bottom of the file, but I think I commented it out because it's buggy:

  // To add a jumping effect later, maybe
  // if (cursors.up.isDown && peter.body.touching.down && hitGround) {
  //   peter.frame = 4;
  //   peter.body.velocity.y = -150;
  // }

**Comment by jamiemccarthy** [comment]
I'll tackle this, it sounds fun.

It could enhance gameplay by making him move faster but not be turnable until he lands...
